language: android

android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-16

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - nvm install stable
  - node --version

install:
  - npm install -g codecov
  - npm install
  - npm install yarn -g
  - yarn
  
script:
  - npm test -- -u
  - npm run lint
  - codecov
  - cd android && ./gradlew assembleRelease

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
