language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install
  - npm install yarn -g
  - yarn
  
script:
  - npm test -- -u
  - npm run lint
  - codecov

notifications:
  email: false
